/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triagemeletronica.interfaces.administrador;

import triagemeletronica.conexao.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Fabricio Sousa
 */
public class Tela_Administrador_Relatorios_Listar_Medicos extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Tela_Agenda_Adicionar
     */
    public Tela_Administrador_Relatorios_Listar_Medicos() {
        initComponents();
        conexao = Conexao.getConnection();
    }
     
        private void pesquisar (){
        
        String sql = "select u.nome AS Nome, u.login AS CRM,e.TELEFONE_FIXO AS Fixo,e.TELEFONE_CELULAR AS Celular,e.ENDERECO AS Endereço\n"
                + "from usuarios as U"
                + " inner join medico as e on u.id = e.id";
        
        try {
            pst = conexao.prepareStatement(sql);     
            rs=pst.executeQuery();
            
             tblRelatorios_Listar_Medicos.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,e);
        }
    }
        
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btbAdd_Fav = new javax.swing.JButton();
        btnCancelar_Fav = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRelatorios_Listar_Medicos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Listar Todos os Medicos");

        btbAdd_Fav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triagemeletronica/icones/Listar.png"))); // NOI18N
        btbAdd_Fav.setToolTipText("Listar");
        btbAdd_Fav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btbAdd_Fav.setPreferredSize(new java.awt.Dimension(100, 100));
        btbAdd_Fav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbAdd_FavActionPerformed(evt);
            }
        });

        btnCancelar_Fav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triagemeletronica/icones/cancelar_listar.png"))); // NOI18N
        btnCancelar_Fav.setToolTipText("Cancelar");
        btnCancelar_Fav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar_Fav.setPreferredSize(new java.awt.Dimension(100, 100));
        btnCancelar_Fav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_FavActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Medicos"));

        tblRelatorios_Listar_Medicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "CRM", "Fixo", "Celular", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRelatorios_Listar_Medicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRelatorios_Listar_MedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRelatorios_Listar_Medicos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(btbAdd_Fav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(btnCancelar_Fav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btbAdd_Fav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar_Fav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        setBounds(0, 0, 840, 740);
    }// </editor-fold>//GEN-END:initComponents

    private void btbAdd_FavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbAdd_FavActionPerformed
      pesquisar();
    }//GEN-LAST:event_btbAdd_FavActionPerformed

    private void btnCancelar_FavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_FavActionPerformed

                this.dispose();
    }//GEN-LAST:event_btnCancelar_FavActionPerformed

    private void tblRelatorios_Listar_MedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRelatorios_Listar_MedicosMouseClicked

        
    }//GEN-LAST:event_tblRelatorios_Listar_MedicosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbAdd_Fav;
    private javax.swing.JButton btnCancelar_Fav;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRelatorios_Listar_Medicos;
    // End of variables declaration//GEN-END:variables
}
